buildscript {
    repositories {
        maven { url 'https://maven.minecraftforge.net' }
        maven { url 'https://repo.spongepowered.org/maven' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3.4'
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'org.spongepowered.mixin'

group            = 'io.github.gotmemes.visbarrier'
archivesBaseName = 'compat_1_12'
version          = '0'

sourceCompatibility = targetCompatibility = 1.8

minecraft {
    version          = '1.12.2-14.23.5.2847'
    runDir           = 'run'
    mappings         = 'stable_39'
    makeObfSourceJar = false
}

mixin {
    add sourceSets.main, "visbarrier_1_12.refmap.json"
}

repositories {
    maven { url 'https://repo.spongepowered.org/maven/' }
}

dependencies {
    compile('org.spongepowered:mixin:0.7.11-SNAPSHOT') {
        exclude module: 'launchwrapper'
        exclude module: 'guava'
        exclude module: 'gson'
        exclude module: 'commons-io'
        exclude module: 'log4j-core'
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

afterEvaluate {
    ['getAssets', 'downloadAssets'].each { name -> tasks.findByName(name)?.enabled = false }
}
